### ISSUE TITLE
Add the IntelliJ configs to .gitignore

### ISSUE THREAD

**Issue by pasinducw** [SLIOI/website#7]

**Comment by pasinducw** [comment]
and remove the current .idea files

**Comment by nmasnadithya** [comment]
Most of the .idea files aren't there, the only files that are there are the files that IntelliJ & GitHub gitignore generator recommends on committing with the project

**Comment by nmasnadithya** [comment]
@pasinducw waiting for your reply

> Most of the .idea files aren't there, the only files that are there are the files that IntelliJ & GitHub gitignore generator recommends on committing with the project
